DRPL-11: Add backend for cm-hero-teaser.
sharique/blt-upstream pull request #10
Opened 2022-03-22 15:14 UTC by ChristianNiemitzRossant

Add Hero-Teaser without demo content

2022-03-23 04:51 UTC, sharique commented
I setup this in local in when importing default content I got following error
```
[error]  Drupal\Core\Database\IntegrityConstraintViolationException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'uid' cannot be null: INSERT INTO "media_field_data" ("mid", "vid", "bundle", "langcode", "status", "uid", "name", "thumbnail__target_id", "thumbnail__alt", "thumbnail__title", "thumbnail__width", "thumbnail__height", "created", "changed", "default_langcode", "revision_translation_affected") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12, :db_insert_placeholder_13, :db_insert_placeholder_14, :db_insert_placeholder_15); Array
(
    [:db_insert_placeholder_0] => 1
    [:db_insert_placeholder_1] => 1
    [:db_insert_placeholder_2] => image
    [:db_insert_placeholder_3] => de
    [:db_insert_placeholder_4] => 1
    [:db_insert_placeholder_5] => 
    [:db_insert_placeholder_6] => 0_Startseite_1900x600_v2.jpg
    [:db_insert_placeholder_7] => 1
    [:db_insert_placeholder_8] => an Image
    [:db_insert_placeholder_9] => 
    [:db_insert_placeholder_10] => 1900
    [:db_insert_placeholder_11] => 600
    [:db_insert_placeholder_12] => 1647903320
    [:db_insert_placeholder_13] => 1647903320
    [:db_insert_placeholder_14] => 1
    [:db_insert_placeholder_15] => 1
)
 in Drupal\Core\Database\Driver\mysql\ExceptionHandler->handleExecutionException() (line 50 of /app/web/core/lib/Drupal/Core/Database/Driver/mysql/ExceptionHandler.php). 

```

2022-03-23 05:35 UTC, sharique commented
If you are not able to fix it, remove default content and we will create is manually.

2022-03-23 06:41 UTC, sharique requested changes

2022-03-23 06:41 UTC, sharique commented on config/default/core.entity_view_display.paragraph.hero_teaser_item.default.yml
> +      view_mode: media_library
Create new display mode to default, will check during in front end implementation how to show based on field value.

2022-03-23 06:41 UTC, sharique commented on config/default/core.entity_view_display.paragraph.hero_teaser_item.default.yml
> +  field_headline_hti:
use existing headline field.

2022-03-23 06:41 UTC, sharique commented on config/default/core.entity_view_display.paragraph.hero_teaser_item.default.yml
> +  field_link_url: true
Change field name to field_link only.

2022-03-23 06:41 UTC, sharique commented on config/default/field.field.paragraph.hero_teaser.field_display_indicators.yml
> +  off_label: 'Off'
Change labels to Yes and No.

2022-03-23 06:41 UTC, sharique commented on config/default/field.field.paragraph.hero_teaser_item.field_link_url.yml
> +label: 'Link URL'
Change label to `Link`

2022-03-23 06:46 UTC, sharique requested changes

2022-03-23 06:46 UTC, sharique commented on config/default/core.entity_view_display.paragraph.hero_teaser.default.yml
> +    label: above
Hide label.

2022-03-23 06:46 UTC, sharique commented on config/default/field.storage.paragraph.field_headline_hti.yml
> +id: paragraph.field_headline_hti
Use existing headline field.

2022-03-23 06:46 UTC, sharique commented on config/default/field.storage.paragraph.field_text_align.yml
> +      label: left
Start label with capital letters.

2022-03-23 15:48 UTC, sharique commented on composer.json
> +            }
@ChristianNiemitzRossant you also need to commit updated composer.lock after applying patch.  There might be some conflict with composer.lock, as I updated drupal core.

2022-03-23 16:16 UTC, ChristianNiemitzRossant commented on composer.json
> +            }
I hopefully solved it.

2022-03-23 17:13 UTC, ChristianNiemitzRossant commented
Unconflicted.

2022-03-24 13:47 UTC, sharique commented
merge but few small changes can be added in next PR.

- Use default display mode for media display.
- For Media hide media name.
- In default content add one video also.

2022-03-24 13:47 UTC, merged